### ISSUE TITLE
Error when running "cargo build"

### ISSUE THREAD

**Issue by loureirorg** [maidsafe/system_uri#18]
- **OS:** _Ubuntu 16.10 64-bits_
- **rustc --version:** _rustc 1.16.0 (30cf806ef 2017-03-10)_
- **cargo --version:** _cargo-0.17.0-nightly (f9e5481 2017-03-03)_
- **Terminal:**
```bash
$ cargo build
   Compiling ffi_utils v0.1.0 (https://github.com/maidsafe/safe_client_libs.git?branch=dev#3ba1cb67)
error: struct field shorthands are unstable (see issue #37340)
  --> /home/daniel/.cargo/git/checkouts/safe_client_libs-e3345e9360262bab/3ba1cb6/ffi_utils/src/catch_unwind.rs:54:21
   |
54 |                     error_code,
   |                     ^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `ffi_utils`.

To learn more, run the command again with --verbose.
```

**Comment by penguwin** [comment]
*Not a mantainer here*
As far as I know, the related field shorthand initializiers are made stable since [1.7](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1170-2017-04-27).
Therefore we can close this issue :-)
